### ISSUE TITLE
Fatal error generating rss feed when video url is missing

### ISSUE THREAD

**Issue by qoijjj** [pablouser1/ProxiTok#143]
Before submitting an issue, please make sure you are using the latest version of ProxiTok.

**Describe the bug**

Only occurs on accounts with missing video urls. The rss feed generation hits a fatal error instead of outputting a complete rss feed. Based on the logs, it looks like this can be fixed by adding a null check before trying to operate on the url in Wrappers.php.

**To Reproduce**

**Expected behavior**
RSS feed should be generated but with that single video missing instead of crashing.

**Logs**

`<b>Warning</b>:  Undefined property: stdClass::$playAddr in <b>/cache/templates-views-rss.latte--58b1ca4d29.php</b> on line <b>42</b><br />
<br />
<b>Fatal error</b>:  Uncaught TypeError: App\Helpers\Wrappers::App\Helpers\{closure}(): Argument #1 ($url) must be of type string, null given, called in /cache/templates-views-rss.latte--58b1ca4d29.php on line 42 and defined in /var/www/html/app/Helpers/Wrappers.php:75
Stack trace:
#0 /cache/templates-views-rss.latte--58b1ca4d29.php(42): App\Helpers\Wrappers::App\Helpers\{closure}(NULL)
#1 /var/www/html/vendor/latte/latte/src/Latte/Runtime/Template.php(171): Template58b1ca4d29-&gt;main()
#2 /var/www/html/vendor/latte/latte/src/Latte/Engine.php(102): Latte\Runtime\Template-&gt;render(NULL)
#3 /var/www/html/app/Helpers/Wrappers.php(128): Latte\Engine-&gt;render('/var/www/html/a...', Object(App\Models\RSSTemplate))
#4 /var/www/html/app/Controllers/UserController.php(47): App\Helpers\Wrappers::latte('rss', Object(App\Models\RSSTemplate))
#5 [internal function]: App\Controllers\UserController::rss('anastasyakh')
#6 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array(Array, Array)
#7 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router-&gt;invoke('UserController@...', Array)
#8 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router-&gt;handle(Array, true)
#9 /var/www/html/index.php(17): Bramus\Router\Router-&gt;run()
#10 {main}
  thrown in <b>/var/www/html/app/Helpers/Wrappers.php</b> on line <b>75</b><br />`

**Enviroment (please complete the following information):**

- Deployment method (if possible): [e.g docker, heroku, manual...]
- Frontend version: 2.4.9.0
- Scrapper version: 2.3.6.4
- PHP Version: [e.g. 8.0]

You can find the frontend and scrapper version on /about

**Comment by xbdmHQ** [comment]
Try mines, I tested my RSS Feeds. It's working for me:
https://cringe.xbdm.fun/

**Comment by qoijjj** [comment]
> Try mines, I tested my RSS Feeds. It's working for me: https://cringe.xbdm.fun/

It happens very occasionally. Once in a while, tiktok will return a null value for the link. ProxiTok doesn't do a null check when generating the rss, so it breaks.

**Comment by xbdmHQ** [comment]
> > Try mines, I tested my RSS Feeds. It's working for me: https://cringe.xbdm.fun/
> 
> It happens very occasionally. Once in a while, tiktok will return a null value for the link. ProxiTok doesn't do a null check when generating the rss, so it breaks.

mines a bit edited
