### ISSUE TITLE
Trending doesn't work if the "Legacy mode" isn't set

### ISSUE THREAD

**Issue by TheFrenchGhosty** [pablouser1/ProxiTok#21]
If the "Legacy mode" setting to "Off" (and a cookie is saved), the trending won't work, and will just show an error page:

This settings should ideally be set instance-wide, with an environment variable.

```
Fatal error: Uncaught TypeError: TikScraper\Models\Meta::getCode(): Return value must be of type int, none returned in /var/www/html/vendor/pablouser1/tikscraper/src/Models/Meta.php:29 Stack trace: #0 /var/www/html/vendor/pablouser1/tikscraper/src/Models/Meta.php(16): TikScraper\Models\Meta->getCode(Object(stdClass)) #1 /var/www/html/vendor/pablouser1/tikscraper/src/Models/Feed.php(37): TikScraper\Models\Meta->__construct(true, 200, Object(stdClass)) #2 /var/www/html/vendor/pablouser1/tikscraper/src/Api.php(36): TikScraper\Models\Feed->fromReq(Object(TikScraper\Models\Response), NULL, '') #3 /var/www/html/app/Controllers/TrendingController.php(19): TikScraper\Api->getTrending('') #4 [internal function]: App\Controllers\TrendingController::get() #5 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array(Array, Array) #6 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke('TrendingControl...', Array) #7 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true) #8 /var/www/html/index.php(14): Bramus\Router\Router->run() #9 {main} thrown in /var/www/html/vendor/pablouser1/tikscraper/src/Models/Meta.php on line 29
```

**Comment by pablouser1** [comment]
I'm also having this issue locally. I think TikTok is flagging the request as automated. It's also not returning the usual VERIFY_CODE error so that's why PHP crashes. I'm investigating the issue

**Comment by pablouser1** [comment]
Ok, it is now "fixed". For now if you use Standard mode it will return a "No items sent by TikTok!" message (which I guess is way better than just crashing) and if you use Legacy mode you get a normal response.
@TheFrenchGhosty I ran your docker image and I got those results.

I'll try to get Standard mode to return a normal response
