### ISSUE TITLE
 Fatal error: Uncaught Error: Typed property TikScraper\Models\Info::$detail must not be accessed before initialization in /var/www/html/vendor/pablouser1/tikscraper/src/Legacy.php:39 Stack trace: #0 /var/www/html/app/Controllers/UserController.php(13): TikScraper\Legacy->getUserFeed('roro.cat', 0) #1 [internal function]: App\Controllers\UserController::get('roro.cat') #2 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array(Array, Array) #3 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke('UserController@...', Array) #4 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true) #5 /var/www/html/index.php(14): Bramus\Router\Router->run() #6 {main} thrown in /var/www/html/vendor/pablouser1/tikscraper/src/Legacy.php on line 39

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [pablouser1/ProxiTok#29]
Each time I try to visit URL I get ``` Fatal error: Uncaught Error: Typed property TikScraper\Models\Info::$detail must not be accessed before initialization in /var/www/html/vendor/pablouser1/tikscraper/src/Legacy.php:39 Stack trace: #0 /var/www/html/app/Controllers/UserController.php(13): TikScraper\Legacy->getUserFeed('roro.cat', 0) #1 [internal function]: App\Controllers\UserController::get('roro.cat') #2 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array(Array, Array) #3 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke('UserController@...', Array) #4 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true) #5 /var/www/html/index.php(14): Bramus\Router\Router->run() #6 {main} thrown in /var/www/html/vendor/pablouser1/tikscraper/src/Legacy.php on line 39```

So any ideas how to fix it? I use docker and link is: https://proxitok.esmailelbob.xyz/@roro.cat

**Comment by EsmailELBoBDev2** [comment]
oh oh nvm I'm stupid

I forgot to rebuild docker image I thought I added docker image but it was build files my bad I'm sorry
