### ISSUE TITLE
Trending broken - TikScraper\Models\Feed::setNav(): Argument #3 ($maxCursor) must be of type string, null given,

### ISSUE THREAD

**Issue by TheFrenchGhosty** [pablouser1/ProxiTok#37]
```
Fatal error: Uncaught TypeError: TikScraper\Models\Feed::setNav(): Argument #3 ($maxCursor) must be of type string, null given, called in /var/www/html/vendor/pablouser1/tikscraper/src/Models/Feed.php on line 62 and defined in /var/www/html/vendor/pablouser1/tikscraper/src/Models/Feed.php:17 Stack trace: #0 /var/www/html/vendor/pablouser1/tikscraper/src/Models/Feed.php(62): TikScraper\Models\Feed->setNav(false, NULL, NULL) #1 /var/www/html/vendor/pablouser1/tikscraper/src/Items/Trending.php(43): TikScraper\Models\Feed->fromReq(Object(TikScraper\Models\Response), NULL, '') #2 /var/www/html/vendor/pablouser1/tikscraper/src/Items/Trending.php(27): TikScraper\Items\Trending->feedStandard('') #3 /var/www/html/app/Controllers/TrendingController.php(21): TikScraper\Items\Trending->feed('') #4 [internal function]: App\Controllers\TrendingController::get() #5 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array(Array, Array) #6 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke('TrendingControl...', Array) #7 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true) #8 /var/www/html/index.php(17): Bramus\Router\Router->run() #9 {main} thrown in /var/www/html/vendor/pablouser1/tikscraper/src/Models/Feed.php on line 17
```

See: https://proxitok.pussthecat.org/trending

**Comment by TheFrenchGhosty** [comment]
Well, it works now, so maybe just a temporary bug.
