### ISSUE TITLE
Redis connection times out

### ISSUE THREAD

**Issue by artemislena** [pablouser1/ProxiTok#77]
**Describe the bug**
T.: We set up an instance at https://tok.artemislena.eu, using the SignTok n ProxiTok container images, n a local password-requiring Redis instance (which listens on the `cni-podman0` interface, i.e. `10.88.0.1`). Now, any search (n presumably any operation that requires Redis) returns an error.

**To Reproduce**
1. Try out some test search. E.g. https://tok.artemislena.eu/@test
2. Wait for a long time.
3. Get an error message. 

**Expected behavior**
The search shows up *something*? Dunno.

**Logs**
```
Fatal error: Uncaught RedisException: Connection timed out in /var/www/html/app/Cache/RedisCache.php:10 Stack trace: #0 /var/www/html/app/Cache/RedisCache.php(10): Redis->connect('10.88.0.1', 6379) #1 /var/www/html/app/Helpers/Wrappers.php(96): App\Cache\RedisCache->__construct('10.88.0.1', 6379, 'u8gM9B794vsUVH4...') #2 /var/www/html/app/Controllers/UserController.php(14): App\Helpers\Wrappers::api() #3 [internal function]: App\Controllers\UserController::get('test') #4 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array(Array, Array) #5 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke('UserController@...', Array) #6 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true) #7 /var/www/html/index.php(17): Bramus\Router\Router->run() #8 {main} thrown in /var/www/html/app/Cache/RedisCache.php on line 10
```

**Enviroment (please complete the following information):**

- Deployment method (if possible): docker
- Frontend version: 2.4.0.0
- Scrapper version: 2.2.1.0
- PHP Version: Whatever the Docker image ships w atm

**Comment by artemislena** [comment]
Nvm. Forgota open the port in the firewall.
